version: '3.3'

services:
  app:
    build: .
    command: python -u run.py
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    links:
      - db
    # depends_on:
    #   - db
    # environment:
    #   - MONGO_URI=mongodb://test_mongodb:27017/student_db
    # networks:
    #   - be-data

  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=student_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      # - mongo_data:/data/db
    ports:
      - 27017:27017
#     networks:
#       - be-data

# networks:
#   be-data:
#     driver: bridge

volumes:
  mongo_data:
