apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA== # 'root' encoded in base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzcw== # 'pass' encoded in base64
