apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-service
spec:
  type: NodePort
  selector:
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017
