apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha-helm-api-multisource
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: vdt-api
  source:
    repoURL: https://github.com/nguyenha-meiii/vdt_midterm_api
    path: helm-api
    targetRevision: HEAD
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/nguyenha-meiii/api_config/HEAD/values.yaml