name: Continuous Delivery Docker Image for API

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v2
        id: buildx 
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta2
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/vdt_api

      - name: Build and Push Docker API Image
        uses: docker/build-push-action@v4
        id: docker_build_backend
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta2.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max